package meta

import (
	"fmt"
	"reflect"
	"slices"
	"time"
)

func (g *generator) renderPrologue() {
	g.fprintf(`
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %%+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)
`)
}

func (g *generator) renderDriverScan(t reflect.Type) {
	g.fprintf("func (v *%s) Scan(thing any) (err error) {", t.Name())
	g.addImport("strconv")
	switch t.Kind() {
	case reflect.Slice:
		g.renderPrologue()
		g.fprintf(`
	if source[0] != '{' || source[len(source)-1] != '}' {
		return fmt.Errorf("bad source string: %%q", source)
	}
	source = source[1 : len(source)-1]
	sourceLen = len(source)
	sourceBytes = unsafeBytes(source)

	var items = make([]%s, 0)
	for cur := 0; cur < sourceLen; {
		var n int
		var a string
		if a, n, err = readString(sourceBytes[cur:]); err != nil {
			return err
		}
		cur += n + 1
		items = append(items, %s{})
		if err = items[len(items)-1].Scan(a); err != nil {
			return err
		}
	}

	*v = items
`, t.Elem().Name(), t.Elem().Name())
		if !slices.Contains(g.seenAlreadyTypes, t.Elem()) {
			g.seenAlreadyTypes = append(g.seenAlreadyTypes, t.Elem())
			g.needMoreTypes = append(g.needMoreTypes, t.Elem())
		}
		// g.parseInto(t, ",", "*v")
	case reflect.Pointer:
		panic("cant parse pointers yet")
	case reflect.Struct:
		g.renderPrologue()
		g.fprintf(`
	if sourceBytes[0] != '(' || sourceBytes[sourceLen-1] != ')' {
		return fmt.Errorf("bad source string: %%q", source)
	}
	var cur = 1
`)
		for i := range t.NumField() {
			var field = t.Field(i)
			if !field.IsExported() {
				continue
			}
			if i == t.NumField()-1 {
				g.renderStructField(field.Type, ")", "v.%s", field.Name)
			} else {
				g.renderStructField(field.Type, ",", "v.%s", field.Name)
			}
		}
	default:
		panic("bad type:" + t.String())

	}
	g.fprintf("\treturn nil\n}\n\n")
}

func (g *generator) renderStringParser(target string) {
	g.fprintf(`
	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		%s = next
	}
`, target)

}

func (g *generator) renderIntegerParser(delim, target string, t reflect.Type) {
	g.addImport("strconv")
	g.fprintf(`
	{
		var startIntField = cur
		for ; source[cur] != '%s'; cur++ {
		}
		var answer int64
		if answer, err = strconv.ParseInt(unsafeString(sourceBytes[startIntField:cur]), 10, 64); err != nil {
			return err
		}
		%s = %s(answer)
	}
`, delim, target, t)

}

func (g *generator) renderBooleanParser(delim, target string) {
	g.fprintf(`
	{
		var start = cur
		for ; sourceBytes[cur] != '%s'; cur++ {
		}
		var boolString = unsafeString(sourceBytes[start:cur])
		switch boolString {
		case "t":
			%s = true
		case "f":
			%s = false
		default:
			panic("bad bool string from postgres: " + boolString)
		}
	}
`, delim, target, target)
}

func (g *generator) renderFileHeader(packageName string) {

	g.fprintf(`/*
auto-generated by Custom Type Fuckery Generator v0
date: %s
I hope this does not ruin your production.
@abk 
*/
`, time.Now())
	g.fprintf("package %s\n\n", packageName)
	g.fprintf("import (\n")
	for _, item := range g.importsNeeded {
		g.fprintf("\t%q\n", item)
	}
	g.fprintf(")\n\n")
	g.fprintf(`

func unsafeString(bts []byte) string {
	return unsafe.String(unsafe.SliceData(bts), len(bts))
}

func unsafeBytes(str string) []byte {
	return unsafe.Slice(unsafe.StringData(str), len(str))
}

// bad
func readString(b []byte) (res string, read int, err error) {
	switch b[0] {
	case '"':
		var buf bytes.Buffer
		for i := 1; i < len(b); i++ {
			var n = b[i]
			switch n {
			case '"':
				i++
				if i == len(b) {
					return buf.String(), i, nil
				} else if n = b[i]; n == '"' {
					buf.WriteByte('"')
				} else {
					return buf.String(), i, nil
				}
			case '\\':
				i++
				if i == len(b) {
					return "", 0, fmt.Errorf("bad escape sequence: %%q", string(b))
				}
				n = b[i]
				switch n {
				case '"':
					buf.WriteByte('"')
				case '\\':
					buf.WriteByte('\\')
				default:
					return "", 0, fmt.Errorf("bad escape sequence: %%q", string(b))
				}
			default:
				buf.WriteByte(n)
			}
		}
		return "", 0, fmt.Errorf("bad escaped string literal: %%s", string(b))
	default:
		for i := 0; i < len(b); i++ {
			switch b[i] {
			case ')', '}', ',':
				return string(b[:i]), i, nil
			}
		}
		return "", 0, fmt.Errorf(` + "`readString should be called only for '\"', '{' or '(' - delimited strings or records or array literals`" + `)
	}
}

const quotedCurlyLeft = ` + "`\"{\"`" + `
const quotedCurlyRight = ` + "`\"}\"`" + `
const quotedComma = ` + "`\",\"`" + `

`)
}

func (g *generator) renderSliceParser(t reflect.Type, target string) {
	if t.Kind() == reflect.Struct && !slices.Contains(g.seenAlreadyTypes, t) {
		g.needMoreTypes = append(g.needMoreTypes, t)
		g.seenAlreadyTypes = append(g.seenAlreadyTypes, t)
	}
	g.fprintf(`
	{
		var str, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		str = str[1 : len(str)-1]
		cur += n
		var items = make([]%s, 0)
		for cur := 0; cur < len(str)-1; {
			var n int
			var a string
			if a, n, err = readString(unsafeBytes(str[cur:])); err != nil {
				return err
			}
			cur += n + 1
			items = append(items, %s{})
			if err = items[len(items)-1].Scan(a); err != nil {
				return err
			}
		}
		%s = items
	}
`, t.Name(), t.Name(), target)
	g.addImport("bytes", "strings")
}

func (g *generator) renderStructField(t reflect.Type, delim string, format string, a ...any) {
	var target = fmt.Sprintf(format, a...)
	switch t.Kind() {
	case reflect.Slice:
		var elemType = t.Elem()
		g.renderSliceParser(elemType, target)
	case reflect.String:
		g.renderStringParser(target)
	case reflect.Int:
		g.renderIntegerParser(delim, target, t)
	case reflect.Bool:
		g.renderBooleanParser(delim, target)
	default:
		g.fprintf("\tpanic(\"type %s is unparseable now\")\n", t.Name())
	}
	g.fprintf("\tcur++\n")
}
