/*
auto-generated by Custom Type Fuckery Generator v0
date: 2024-10-29 12:40:49.29072875 +0300 MSK m=+0.000080211
I hope this does not ruin your production.
@abk 
*/
package types

import (
	"unsafe"
	"database/sql/driver"
	"fmt"
	"strconv"
	"bytes"
	"strings"
)



func unsafeString(bts []byte) string {
	return unsafe.String(unsafe.SliceData(bts), len(bts))
}

func unsafeBytes(str string) []byte {
	return unsafe.Slice(unsafe.StringData(str), len(str))
}

// bad
func readString(b []byte) (res string, read int, err error) {
	switch b[0] {
	case '"':
		var buf bytes.Buffer
		for i := 1; i < len(b); i++ {
			var n = b[i]
			switch n {
			case '"':
				i++
				if i == len(b) {
					return buf.String(), i, nil
				} else if n = b[i]; n == '"' {
					buf.WriteByte('"')
				} else {
					return buf.String(), i, nil
				}
			case '\\':
				i++
				if i == len(b) {
					return "", 0, fmt.Errorf("bad escape sequence: %q", string(b))
				}
				n = b[i]
				switch n {
				case '"':
					buf.WriteByte('"')
				case '\\':
					buf.WriteByte('\\')
				default:
					return "", 0, fmt.Errorf("bad escape sequence: %q", string(b))
				}
			default:
				buf.WriteByte(n)
			}
		}
		return "", 0, fmt.Errorf("bad escaped string literal: %s", string(b))
	default:
		for i := 0; i < len(b); i++ {
			switch b[i] {
			case ')', '}', ',':
				return string(b[:i]), i, nil
			}
		}
		return "", 0, fmt.Errorf(`readString should be called only for '"', '{' or '(' - delimited strings or records or array literals`)
	}
}

const quotedCurlyLeft = `"{"`
const quotedCurlyRight = `"}"`
const quotedComma = `","`

func (v *Containers) Scan(thing any) (err error) {
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)

	if source[0] != '{' || source[len(source)-1] != '}' {
		return fmt.Errorf("bad source string: %q", source)
	}
	source = source[1 : len(source)-1]
	sourceLen = len(source)
	sourceBytes = unsafeBytes(source)

	var items = make([]Container, 0)
	for cur := 0; cur < sourceLen; {
		var n int
		var a string
		if a, n, err = readString(sourceBytes[cur:]); err != nil {
			return err
		}
		cur += n + 1
		items = append(items, Container{})
		if items[len(items)-1].Scan(a); err != nil {
			return err
		}
	}

	*v = items
	return nil
}


func (v Containers) Value() (t driver.Value, err error) {
	var b strings.Builder

	{
		b.WriteByte('{')
		for i := range v {

		var thing string
		{
			var valued, e = v[i].Value()
			if e != nil {
				return nil, e
			}
			switch val := valued.(type) {
			case string:
				thing = strconv.Quote(val)
			case nil:
				// do nothing since why
			default:
				panic("TODO: bad thing")
			}
		}

			b.WriteString(thing)
			if i != len(v)-1 {
				b.WriteByte(',')
			}
		}
		b.WriteByte('}')
	}
		
	return b.String(), nil
}
func (v *Props) Scan(thing any) (err error) {
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)

	if source[0] != '{' || source[len(source)-1] != '}' {
		return fmt.Errorf("bad source string: %q", source)
	}
	source = source[1 : len(source)-1]
	sourceLen = len(source)
	sourceBytes = unsafeBytes(source)

	var items = make([]Prop, 0)
	for cur := 0; cur < sourceLen; {
		var n int
		var a string
		if a, n, err = readString(sourceBytes[cur:]); err != nil {
			return err
		}
		cur += n + 1
		items = append(items, Prop{})
		if items[len(items)-1].Scan(a); err != nil {
			return err
		}
	}

	*v = items
	return nil
}


func (v Props) Value() (t driver.Value, err error) {
	var b strings.Builder

	{
		b.WriteByte('{')
		for i := range v {

		var thing string
		{
			var valued, e = v[i].Value()
			if e != nil {
				return nil, e
			}
			switch val := valued.(type) {
			case string:
				thing = strconv.Quote(val)
			case nil:
				// do nothing since why
			default:
				panic("TODO: bad thing")
			}
		}

			b.WriteString(thing)
			if i != len(v)-1 {
				b.WriteByte(',')
			}
		}
		b.WriteByte('}')
	}
		
	return b.String(), nil
}

func (v *NullableHTTPParams) Scan(thing any) (err error) {
	switch thval := thing.(type) {
	case nil:
		v.Valid = false
		return
	case string:
		v.Valid = true
		v.Item = new(HTTPParams)
		return v.Item.Scan(thval)
	default:
		panic("bad type from posthres: " + fmt.Sprint(thval))
	}
}

func (v *NullableHTTPParams) Value() (t driver.Value, err error) {
	if v.Valid {
		return v.Item.Value()
	} else {
		return nil, nil
	}
}
func (v *Container) Scan(thing any) (err error) {
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)

	if sourceBytes[0] != '(' || sourceBytes[sourceLen-1] != ')' {
		return fmt.Errorf("bad source string: %q", source)
	}
	var cur = 1

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.DefaultCpuLimit = next
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.DefaultCpuRequest = next
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.DefaultMemoryLimit = next
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.DefaultMemoryRequest = next
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.ContainerName = next
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.ContainerImage = next
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.ContainerImageTag = next
	}
	cur++

	{
		var str, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		str = str[1 : len(str)-1]
		cur += n
		var items = make([]Option, 0)
		for cur := 0; cur < len(str)-1; {
			var n int
			var a string
			if a, n, err = readString(unsafeBytes(str[cur:])); err != nil {
				return err
			}
			cur += n + 1
			items = append(items, Option{})
			if items[len(items)-1].Scan(a); err != nil {
				return err
			}
		}
		v.ConfigurationOptions = items
	}
	cur++
	return nil
}


func (v *Container) Value() (t driver.Value, err error) {
	var b strings.Builder

	b.WriteByte('(')
	{

		var thing = strconv.Quote(v.DefaultCpuLimit)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.DefaultCpuRequest)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.DefaultMemoryLimit)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.DefaultMemoryRequest)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.ContainerName)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.ContainerImage)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.ContainerImageTag)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing string
		var thingBuilder strings.Builder
		thingBuilder.WriteString("{")
		for i := range v.ConfigurationOptions {

		var thing string
		{
			var valued, e = v.ConfigurationOptions[i].Value()
			if e != nil {
				return nil, e
			}
			switch val := valued.(type) {
			case string:
				thing = strconv.Quote(val)
			case nil:
				// do nothing since why
			default:
				panic("TODO: bad thing")
			}
		}

			thingBuilder.WriteString(thing)
			if i != len(v.ConfigurationOptions)-1 {
				thingBuilder.WriteString(",")
			}
		}
		thingBuilder.WriteString("}")
		thing = strconv.Quote(thingBuilder.String())

		b.WriteString(thing)
	}
	
	b.WriteByte(')')

	return b.String(), nil
}
func (v *Prop) Scan(thing any) (err error) {
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)

	if sourceBytes[0] != '(' || sourceBytes[sourceLen-1] != ')' {
		return fmt.Errorf("bad source string: %q", source)
	}
	var cur = 1

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.Key = next
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.Val = next
	}
	cur++
	return nil
}


func (v *Prop) Value() (t driver.Value, err error) {
	var b strings.Builder

	b.WriteByte('(')
	{

		var thing = strconv.Quote(v.Key)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.Val)

		b.WriteString(thing)
	}
	
	b.WriteByte(')')

	return b.String(), nil
}
func (v *HTTPParams) Scan(thing any) (err error) {
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)

	if sourceBytes[0] != '(' || sourceBytes[sourceLen-1] != ')' {
		return fmt.Errorf("bad source string: %q", source)
	}
	var cur = 1

	{
		var startIntField = cur
		for ; source[cur] != ','; cur++ {
		}
		var answer int64
		if answer, err = strconv.ParseInt(unsafeString(sourceBytes[startIntField:cur]), 10, 64); err != nil {
			return err
		}
		v.Port = int(answer)
	}
	cur++

	{
		var str, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		str = str[1 : len(str)-1]
		cur += n
		var items = make([]Route, 0)
		for cur := 0; cur < len(str)-1; {
			var n int
			var a string
			if a, n, err = readString(unsafeBytes(str[cur:])); err != nil {
				return err
			}
			cur += n + 1
			items = append(items, Route{})
			if items[len(items)-1].Scan(a); err != nil {
				return err
			}
		}
		v.Routes = items
	}
	cur++
	return nil
}


func (v *HTTPParams) Value() (t driver.Value, err error) {
	var b strings.Builder

	b.WriteByte('(')
	{

		var thing = fmt.Sprint(v.Port)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing string
		var thingBuilder strings.Builder
		thingBuilder.WriteString("{")
		for i := range v.Routes {

		var thing string
		{
			var valued, e = v.Routes[i].Value()
			if e != nil {
				return nil, e
			}
			switch val := valued.(type) {
			case string:
				thing = strconv.Quote(val)
			case nil:
				// do nothing since why
			default:
				panic("TODO: bad thing")
			}
		}

			thingBuilder.WriteString(thing)
			if i != len(v.Routes)-1 {
				thingBuilder.WriteString(",")
			}
		}
		thingBuilder.WriteString("}")
		thing = strconv.Quote(thingBuilder.String())

		b.WriteString(thing)
	}
	
	b.WriteByte(')')

	return b.String(), nil
}
func (v *Option) Scan(thing any) (err error) {
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)

	if sourceBytes[0] != '(' || sourceBytes[sourceLen-1] != ')' {
		return fmt.Errorf("bad source string: %q", source)
	}
	var cur = 1

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.Type = next
	}
	cur++

	{
		var start = cur
		for ; sourceBytes[cur] != ','; cur++ {
		}
		var boolString = unsafeString(sourceBytes[start:cur])
		switch boolString {
		case "t":
			v.Required = true
		case "f":
			v.Required = false
		default:
			panic("bad bool string from postgres: " + boolString)
		}
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.Lable = next
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.Name = next
	}
	cur++
	return nil
}


func (v *Option) Value() (t driver.Value, err error) {
	var b strings.Builder

	b.WriteByte('(')
	{

		var thing = strconv.Quote(v.Type)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing string
		if v.Required {
			thing = "t"
		} else {
			thing = "f"
		}

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.Lable)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.Name)

		b.WriteString(thing)
	}
	
	b.WriteByte(')')

	return b.String(), nil
}
func (v *Options) Scan(thing any) (err error) {
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)

	if source[0] != '{' || source[len(source)-1] != '}' {
		return fmt.Errorf("bad source string: %q", source)
	}
	source = source[1 : len(source)-1]
	sourceLen = len(source)
	sourceBytes = unsafeBytes(source)

	var items = make([]Option, 0)
	for cur := 0; cur < sourceLen; {
		var n int
		var a string
		if a, n, err = readString(sourceBytes[cur:]); err != nil {
			return err
		}
		cur += n + 1
		items = append(items, Option{})
		if items[len(items)-1].Scan(a); err != nil {
			return err
		}
	}

	*v = items
	return nil
}


func (v Options) Value() (t driver.Value, err error) {
	var b strings.Builder

	{
		b.WriteByte('{')
		for i := range v {

		var thing string
		{
			var valued, e = v[i].Value()
			if e != nil {
				return nil, e
			}
			switch val := valued.(type) {
			case string:
				thing = strconv.Quote(val)
			case nil:
				// do nothing since why
			default:
				panic("TODO: bad thing")
			}
		}

			b.WriteString(thing)
			if i != len(v)-1 {
				b.WriteByte(',')
			}
		}
		b.WriteByte('}')
	}
		
	return b.String(), nil
}
func (v *Route) Scan(thing any) (err error) {
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)

	if sourceBytes[0] != '(' || sourceBytes[sourceLen-1] != ')' {
		return fmt.Errorf("bad source string: %q", source)
	}
	var cur = 1

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.Path = next
	}
	cur++

	{
		var next, n, e = readString(sourceBytes[cur:])
		if e != nil {
			return e
		}
		cur += n
		v.Method = next
	}
	cur++
	return nil
}


func (v *Route) Value() (t driver.Value, err error) {
	var b strings.Builder

	b.WriteByte('(')
	{

		var thing = strconv.Quote(v.Path)

		b.WriteString(thing)
	}
	
	b.WriteByte(',')
	{

		var thing = strconv.Quote(v.Method)

		b.WriteString(thing)
	}
	
	b.WriteByte(')')

	return b.String(), nil
}
func (v *Routes) Scan(thing any) (err error) {
	var source, ok = thing.(string)
	if !ok {
		return fmt.Errorf("incompatible type: %+v", thing)
	}
	if source[0] == '"' {
		// delimeter here is bogus
		if source, _, err = readString(unsafeBytes(source)[1:]); err != nil {
			return err
		}
	}
	var sourceLen = len(source)
	var sourceBytes = unsafeBytes(source)

	if source[0] != '{' || source[len(source)-1] != '}' {
		return fmt.Errorf("bad source string: %q", source)
	}
	source = source[1 : len(source)-1]
	sourceLen = len(source)
	sourceBytes = unsafeBytes(source)

	var items = make([]Route, 0)
	for cur := 0; cur < sourceLen; {
		var n int
		var a string
		if a, n, err = readString(sourceBytes[cur:]); err != nil {
			return err
		}
		cur += n + 1
		items = append(items, Route{})
		if items[len(items)-1].Scan(a); err != nil {
			return err
		}
	}

	*v = items
	return nil
}


func (v Routes) Value() (t driver.Value, err error) {
	var b strings.Builder

	{
		b.WriteByte('{')
		for i := range v {

		var thing string
		{
			var valued, e = v[i].Value()
			if e != nil {
				return nil, e
			}
			switch val := valued.(type) {
			case string:
				thing = strconv.Quote(val)
			case nil:
				// do nothing since why
			default:
				panic("TODO: bad thing")
			}
		}

			b.WriteString(thing)
			if i != len(v)-1 {
				b.WriteByte(',')
			}
		}
		b.WriteByte('}')
	}
		
	return b.String(), nil
}
